project:
  type: website

website:
  title: "Curriculum vitae"
  navbar:
    background: light
    foreground: gray
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

