---
title: "Timur Mitrofanov"
---

##### [Email](mailto:timur.mitrofanov@gmail.com)           [GitHub](https://github.com/tmhist/)  

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_


### **Education**

-   **Heidelberg University**\
    -   [Weiterbildung "Digital Humanities", 2020 - 2023]{style="color:gray"}\
    -   [Graduate School for the Humanities and Social Sciences, 2019 - 2023, Ph.D. student in Russian history]{style="color:gray"}\
-   **Kazan University**\
    -   [Russian History, 2016 - 2019, Postgraduate student]{style="color:gray"}\
    -   [International and European law, 2009 - 2014, Graduate]{style="color:gray"}\

### **Work**

-   **Centrum für Soziale Investitionen und Innovationen (Forschungsstelle des Max-Weber-Instituts für Soziologie)**\
    [**Position:** Research assistant (Wissenschaftliche Hilfskräft). April 2022 -- June 2024.\
    **Duties:** literature search and review, assistance in writing articles and applying for grants, site management, web scraping]{style="color:gray"}\

-   **Herder-Institut für historische Ostmitteleuropaforschung -- Institut der Leibniz-Gemeinschaft, Digitale Forschungs- und Informationsinfrastrukturen**\
    [**Position:** Research assistant (Wissenschaftliche Hilfskräft). September 2023 -- June 2024.\
    **Duties:** literature search and review, working with various OCR (optical character recognition) tools and testing them, writing Python scripts]{style="color:gray"}\

### **Research interests**

[Eastern European history, Russian history, legal history, rural societies, customary law, local self-government, social history, sociology, digital humanities, digital methods in history, OCR, computer vision, data visualization]{style="color:gray"}\

### **Skills**

[Python (Tesseract, Pandas, NumPy, Seaborn), R (ggplot2), Quarto, GIT, TEI, XML, CSS, Optical Character Recognition (Transkribus, eScriptorium, Google Vision API, OpenCV, spaCy, Nopaque, recognAIze). Software (MS Office, Visual Studio Code, RStudio, Jupyter Notebook, Docker)]{style="color:gray"}

### **Grants and scholarships**

-   [Graduate School Scholarship Programme 2018, provided by DAAD for funding a Ph.D. research project at the Heidelberg Graduate School for the Humanities and Social Sciences, Heidelberg University (2019 -- 2023);]{style="color:gray"}
-   [Research grant for doctoral students, provided by Deutsches Historisches Institut Moskau (February 2019 - March 2019);]{style="color:gray"}
-   [Travel grant provided by 4EU+ Alliance and Erasmus+ programme (July 2022).]{style="color:gray"}

### **Courses**

-   **GESIS Leibniz Institut für Sozialwissenschaften:**
    -   [Applied Data Visualization (9 - 12.05 2023)]{style="color:gray"}\
    -   [Advanced R Programming" (31.05 - 2.06 2023)]{style="color:gray"}\
    -   [Automated Reports & Co with Quarto and Markdown (19 - 20.06 2023)]{style="color:gray"}\
-   **The European University at Saint Petersburg:**
    -   ["Nations and Nationalisms - Concepts, Models, Conceptions". Lecturer: Prof. Dr. A. I. Miller (21.09.2021 - 10.01.2022).]{style="color:gray"}\

### **Workshops, seminars and summer schools**

-   ["Sapere Aude: Freedom and Responsibility", organized by the Association of Schools of Political Studies, in collaboration with the Stockholm Institute of Transition Economics. Stockholm, 23.04.2018 - 28.04.2018;]{style="color:gray"}\
-   ["From the Baltic Sea to the Pacific Ocean: A Shared History of Northern Eurasia". (KRES Poliskola and Ab Imperio journal) 17.07.17 - 29.07.17, Riga;]{style="color:gray"}\
-   [EU Study Week in Volgograd organized by EU Delegation to Russia, 24 - 26 March 2018;]{style="color:gray"}\
-   [Max Planck Summer Academy for Legal History 2018: The World and the Village. The Global and the Local in Legal History. Frankfurt am Main, 16 July - 27 July 2018;]{style="color:gray"}\
-   ["21st Century Risks and Opportunities -- The Politics of Withdrawal", organized by Heidelberg Graduate School for the Humanities and Social Sciences. Heidelberg, 11.10.2019;]{style="color:gray"}\
-   [The research project presentation at the HGGS Research Colloquium, Heidelberg Graduate School for the Humanities and Social Sciences, 10.12.19;]{style="color:gray"}\
-   [C-CAMP Project: AI, Digitalization, Data and Creativity. 11-13 July 2022, Prague;]{style="color:gray"}\
-   ["In Search of Lost Universalism" organized by the Association of Schools of Political Studies of the Council of Europe with support from Heinrich-Böll Stiftung. Berlin, 6-7.12.2023;]{style="color:gray"} 
-   [The thesis presentation at the colloquium at the Department of Eastern European History at the University of Münster. 15.04.2024.]{style="color:gray"}\

### **Conferences**

-   ["Governing and Governance in the Russian Empire in the 18th - early 20th centuries". The European University at Saint Petersburg, 25-27.11.2021;]{style="color:gray"}\
-   ["The history of civilizations and cultures: trends and regional originality". Kazan Federal University, 30.01.2019;]{style="color:gray"}\
-   [International Scientific Conference of Students and Young Scientists "Lomonosov-2018". Moscow State University, 13.04.2018 (Diploma for the best presentation);]{style="color:gray"}\
-   ["Annual Scientific Conference 2017". Kazan Federal University, 30.01.2018.]{style="color:gray"}\

### **Research Internship**

-   [Justus Liebig University Giessen, Department of Eastern European history (16.10.17 - 26.10.17).]{style="color:gray"}\

### **Peer-reviewed publications**

-   [Mitrofanov T.S. The Volost' Courts of Kazan province: legal consciousness, law and customs. IN: Echo of Centuries, 2019, no. 1, pp. 170 - 180. [Link](https://drive.google.com/file/d/0B1YJsH2cBfxKYnhHcVpybmZBTVRPYXVHZDVuWGo4cDFpalln/view?resourcekey=0-k1Lme70vfa7gEx112OAMlg);]{style="color:gray"}
-   [Mitrofanov T.S. The correlation of the law and customs in volost' courts of post-reform Russia (the historiography of the issue). IN: Proceedings of Kazan University. Humanities Series, 2018, vol. 160, no. 3, pp. 643--655. [Link](https://drive.google.com/file/d/0B1YJsH2cBfxKWFVjMnNsN2toX0ZkcHpMOE56ZnhqMTg4UllF/view?resourcekey=0-KfM8uASdSIJwNgDenL2Qtw);]{style="color:gray"}
-   [Litvin A.A., Mitrofanov T.S. Volost' local government in Kazan Province during the first year following the implementation of the Emancipation Reform of 1861. IN: Proceedings of Kazan University. Humanities Series, 2020, vol. 162, no. 1, pp. 35--43. [Link](https://kpfu.ru/uz-ru-hum-2020-1-3.html).]{style="color:gray"}\

### **Languages**

-   [Russian - native;]{style="color:gray"}\
-   [English - advanced;]{style="color:gray"}\
-   [German - intermediate.]{style="color:gray"}\

### **Social and cultural projects, volunteering**

-   [Volunteer in "Kind Hearts" -- a social project organized by the Law Department of the Kazan Federal University in the Kazan Rehabilitation Centre for Children with Special Needs "Solnechny" (Kazan, 2010 -- 2014);]{style="color:gray"}\
-   [Volunteer in the Kazan Federal University's legal clinic (free legal help for people who qualify as low-income (Kazan, 2012-2014);]{style="color:gray"}\
-   [Organizer of lectures, master classes and exhibitions on contemporary art at the Artists and Designers Club "Kineticmax" and in the National Art Gallery "Hazine" (Kazan, 2013 - 2014);]{style="color:gray"}\
-   [Helping Ukrainian refugees in Germany (Heidelberg and Mannheim, 2022-2023).]{style="color:gray"} 

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
