project:
  type: website
  output-dir: docs
  
publish:
  gh-pages:
    deploy: true
    
website:
  title: "Curriculum vitae"
  navbar:
    background: light
    foreground: gray
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

